config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :contacts
    get '404', to: 'application#render404'
    root 'contacts#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def render404
    respond_to do |format|
      format.html { render file: Rails.root.join('public', '404.html'), status: :not_found }
    end
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contact = Contact.new
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.contact_form_submission(@contact).deliver_later
        format.json { render :show, status: :created, location: @contact }
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
      else
        format.json { render json: @contact.errors, status: :unprocessable_entity }
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_params
    params.fetch(:contact, {}).permit(:first_name, :last_name, :phone_number, :email, :message)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="container-contact100">
  <div class="wrap-contact100">
    <%= form_for @contact, html: { id: 'contact-form', class: 'contact100-form validate-form' } do |f|%>
    <span class="contact100-form-title"><%= t('.page_title') %></span>

    <label class="label-input100" for="first_name"><%= t('.name') %> *</label>
    <div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate="<%= t('.field_warnings.first_name') %>">
      <%= f.text_field :first_name, class: 'input100', placeholder: t('activerecord.attributes.contact.first_name') %>
      <span class="focus-input100"></span>
    </div>
    <div class="wrap-input100 rs2-wrap-input100 validate-input" data-validate="<%= t('.field_warnings.last_name') %>">
      <%= f.text_field :last_name, class: 'input100', placeholder: t('activerecord.attributes.contact.last_name')  %>
      <span class="focus-input100"></span>
    </div>

    <label class="label-input100" for="email"><%= t('.email') %> *</label>
    <div class="wrap-input100 validate-input" data-validate="<%= t('.field_warnings.email') %>">
      <%= f.text_field :email, class: 'input100', placeholder: "#{t('global.eg')} example@email.com" %>
      <span class="focus-input100"></span>
    </div>

    <label class="label-input100" for="phone_number"><%= t('.phone_number') %></label>
    <div class="wrap-input100">
      <%= f.text_field :phone_number, class: 'input100', placeholder: "#{t('global.eg')} +1 800 000000" %>
      <span class="focus-input100"></span>
    </div>

    <label class="label-input100" for="message"><%= t('.message') %> *</label>
    <div class="wrap-input100 validate-input" data-validate="<%= t('.field_warnings.message') %>">
      <%= f.text_area :message, class: 'input100', placeholder: t('.message_placeholder') %>
      <span class="focus-input100"></span>
    </div>

    <div class="container-contact100-form-btn">
      <%= f.submit t('.submit'), class: 'contact100-form-btn' %>
    </div>
    <% end %>

    <div class="contact100-more flex-col-c-m" style="background-image: url('/assets/bg-01.jpg')">
      <div class="flex-w size1 p-b-47">
        <div class="txt1 p-r-25">
          <span class="lnr lnr-map-marker"></span>
        </div>
        <div class="flex-col size2">
          <span class="txt1 p-b-20"> <%= t('.address') %> </span>
          <span class="txt2">
            <%= t('.full_address') %>
          </span>
        </div>
      </div>
      <div class="dis-flex size1 p-b-47">
        <div class="txt1 p-r-25">
          <span class="lnr lnr-phone-handset"></span>
        </div>
        <div class="flex-col size2">
          <span class="txt1 p-b-20"> <%= t('.lets_talk') %> </span>
          <span class="txt3"> <%= t('.contact_number') %> </span>
        </div>
      </div>
      <div class="dis-flex size1 p-b-47">
        <div class="txt1 p-r-25">
          <span class="lnr lnr-envelope"></span>
        </div>
        <div class="flex-col size2">
          <span class="txt1 p-b-20"> <%= t('.support') %> </span>
          <span class="txt3"> contact@example.com </span>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="loader-wrapper" class=" loader-wrapper d-none">
  <div class="loader">
    <span></span>
    <span></span>
  </div>
</div>

<%= javascript_include_tag 'contact' %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAjackus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="lang-wrapper">
      <span><%= link_to 'English', root_path(locale: :en) %></span>
      <span><%= link_to 'हिंदी ', root_path(locale: :hi) %></span>
    </div>
    <%= yield %>
  </body>
</html>